##
## Concept    : Multi-Turn Conversations & Token Tracking
## What it does: An interactive programming help chatbot that remembers the full conversation
##               history across multiple turns and tracks cumulative token usage.
## What you'll learn:
##   - Why conversation history matters: the API is stateless, so you must send all
##     previous messages on every request to give the model context
##   - How to grow the messages list by appending both user and assistant messages each turn
##   - How token usage accumulates over a long conversation (important for cost awareness)
##   - The role of the system message in shaping the assistant's personality/scope
##   - Token breakdown per turn:
##       prompt_tokens    = all tokens sent to the model (grows as history grows)
##       completion_tokens = new tokens generated by the model this turn
##       total_tokens     = prompt_tokens + completion_tokens for this API call
## Run: python 5.multi_turn_chatbot.py
##
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

messages=[
    {"role": "system", "content": "You are a programming expert. Answer questions about programming languages. Keep responses short, concise and to the point."}
]

over_all_usage_tokens = 0

print("Welcome to the Programming Help chatbot. Ask me a question!")
while True:
    user_question = input("You: ")
    if user_question.lower() in ["exit", "quit", "bye", "tata"]:
        print("Chatbot: Goodbye! Have a great day!")
        break
    user_message = {"role": "user", "content": user_question}

    messages.append(user_message)

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=messages,
    )

    prompt_tokens = response.usage.prompt_tokens
    completion_tokens = response.usage.completion_tokens
    total_tokens = response.usage.total_tokens
    # Accumulate only completion_tokens — prompt_tokens include the entire history
    # re-sent each turn, so summing total_tokens would double-count past context.
    over_all_usage_tokens += completion_tokens

    assistant_reply = response.choices[0].message.content.strip()

    print("Chat Assistant: ", assistant_reply, "\n")
    print(f"Tokens this turn — prompt: {prompt_tokens}, completion: {completion_tokens}, total: {total_tokens}\n")

    assistant_message = {"role":"assistant", "content": assistant_reply}

    messages.append(assistant_message)

    

print(f"Total completion tokens generated across all turns: {over_all_usage_tokens}")
